In [1]:
from google.colab import drive
import pandas as pd
import numpy as np
#import formatting tools
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Data_For_Collab/Crime_Data_Linear_Reg_Data.csv'
df = pd.read_csv(file_path)

Mounted at /content/drive

In [ ]:
df.head()

,area,victim_age,THEFT OF IDENTITY,77th Street,Central,Devonshire,Foothill,Harbor,Hollenbeck,Hollywood,...,Olympic,Pacific,Rampart,Southeast,Southwest,Topanga,Van Nuys,West LA,West Valley,Wilshire
0,14,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,3,27,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,4,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,10,45,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,6,28,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [5]:
columns_to_drop = ['area', 'victim_age','THEFT OF IDENTITY']
df_corr = df.drop(columns=columns_to_drop, axis=1)
import seaborn as sns
import matplotlib.pyplot as plt

correlation_matrix = df_corr.corr()
print(correlation_matrix)

             77th Street   Central  Devonshire  Foothill    Harbor  \
77th Street     1.000000 -0.073473   -0.053004 -0.047906 -0.051825
Central        -0.073473  1.000000   -0.058734 -0.053085 -0.057428
Devonshire     -0.053004 -0.058734    1.000000 -0.038296 -0.041429
Foothill       -0.047906 -0.053085   -0.038296  1.000000 -0.037444
Harbor         -0.051825 -0.057428   -0.041429 -0.037444  1.000000
Hollenbeck     -0.049921 -0.055318   -0.039907 -0.036068 -0.039019
Hollywood      -0.061177 -0.067791   -0.048905 -0.044201 -0.047817
Mission        -0.052093 -0.057724   -0.041643 -0.037637 -0.040716
N Hollywood    -0.057445 -0.063655   -0.045922 -0.041505 -0.044900
Newton         -0.059607 -0.066051   -0.047650 -0.043067 -0.046590
Northeast      -0.054817 -0.060743   -0.043821 -0.039606 -0.042846
Olympic        -0.060063 -0.066556   -0.048014 -0.043396 -0.046946
Pacific        -0.062524 -0.069284   -0.049982 -0.045174 -0.048870
Rampart        -0.057675 -0.063910   -0.046105 -0.041671 -0.045080
Southeast      -0.059030 -0.065411   -0.047188 -0.042649 -0.046138
Southwest      -0.063287 -0.070129   -0.050592 -0.045726 -0.049466
Topanga        -0.052761 -0.058465   -0.042177 -0.038120 -0.041239
Van Nuys       -0.053149 -0.058894   -0.042487 -0.038400 -0.041542
West LA        -0.055667 -0.061685   -0.044500 -0.040220 -0.043510
West Valley    -0.055145 -0.061107   -0.044083 -0.039843 -0.043103
Wilshire       -0.057378 -0.063580   -0.045868 -0.041456 -0.044847

             Hollenbeck  Hollywood   Mission  N Hollywood    Newton  ...  \
77th Street   -0.049921  -0.061177 -0.052093    -0.057445 -0.059607  ...
Central       -0.055318  -0.067791 -0.057724    -0.063655 -0.066051  ...
Devonshire    -0.039907  -0.048905 -0.041643    -0.045922 -0.047650  ...
Foothill      -0.036068  -0.044201 -0.037637    -0.041505 -0.043067  ...
Harbor        -0.039019  -0.047817 -0.040716    -0.044900 -0.046590  ...
Hollenbeck     1.000000  -0.046060 -0.039221    -0.043251 -0.044878  ...
Hollywood     -0.046060   1.000000 -0.048064    -0.053003 -0.054997  ...
Mission       -0.039221  -0.048064  1.000000    -0.045132 -0.046830  ...
N Hollywood   -0.043251  -0.053003 -0.045132     1.000000 -0.051642  ...
Newton        -0.044878  -0.054997 -0.046830    -0.051642  1.000000  ...
Northeast     -0.041272  -0.050578 -0.043067    -0.047493 -0.049280  ...
Olympic       -0.045221  -0.055418 -0.047188    -0.052037 -0.053995  ...
Pacific       -0.047075  -0.057689 -0.049122    -0.054170 -0.056208  ...
Rampart       -0.043424  -0.053215 -0.045312    -0.049968 -0.051849  ...
Southeast     -0.044443  -0.054464 -0.046377    -0.051142 -0.053067  ...
Southwest     -0.047649  -0.058393 -0.049722    -0.054831 -0.056894  ...
Topanga       -0.039724  -0.048680 -0.041452    -0.045711 -0.047431  ...
Van Nuys      -0.040016  -0.049038 -0.041756    -0.046047 -0.047780  ...
West LA       -0.041912  -0.051362 -0.043734    -0.048228 -0.050043  ...
West Valley   -0.041519  -0.050881 -0.043325    -0.047777 -0.049575  ...
Wilshire      -0.043200  -0.052940 -0.045079    -0.049711 -0.051581  ...

              Olympic   Pacific   Rampart  Southeast  Southwest   Topanga  \
77th Street -0.060063 -0.062524 -0.057675  -0.059030  -0.063287 -0.052761
Central     -0.066556 -0.069284 -0.063910  -0.065411  -0.070129 -0.058465
Devonshire  -0.048014 -0.049982 -0.046105  -0.047188  -0.050592 -0.042177
Foothill    -0.043396 -0.045174 -0.041671  -0.042649  -0.045726 -0.038120
Harbor      -0.046946 -0.048870 -0.045080  -0.046138  -0.049466 -0.041239
Hollenbeck  -0.045221 -0.047075 -0.043424  -0.044443  -0.047649 -0.039724
Hollywood   -0.055418 -0.057689 -0.053215  -0.054464  -0.058393 -0.048680
Mission     -0.047188 -0.049122 -0.045312  -0.046377  -0.049722 -0.041452
N Hollywood -0.052037 -0.054170 -0.049968  -0.051142  -0.054831 -0.045711
Newton      -0.053995 -0.056208 -0.051849  -0.053067  -0.056894 -0.047431
Northeast   -0.049657 -0.051692 -0.047682  -0.048802  -0.052322 -0.043620
Olympic      1.000000 -0.056638 -0.052245  -0.053472  -0.057329 -0.047794
Pacific     -0.056638  1.000000 -0.054386  -0.055664  -0.059679 -0.049752
Rampart     -0.052245 -0.054386  1.000000  -0.051346  -0.055050 -0.045894
Southeast   -0.053472 -0.055664 -0.051346   1.000000  -0.056343 -0.046971
Southwest   -0.057329 -0.059679 -0.055050  -0.056343   1.000000 -0.050359
Topanga     -0.047794 -0.049752 -0.045894  -0.046971  -0.050359  1.000000
Van Nuys    -0.048145 -0.050118 -0.046231  -0.047317  -0.050730 -0.042292
West LA     -0.050426 -0.052493 -0.048421  -0.049558  -0.053133 -0.044296
West Valley -0.049954 -0.052001 -0.047968  -0.049094  -0.052636 -0.043881
Wilshire    -0.051976 -0.054106 -0.049909  -0.051082  -0.054766 -0.045657

             Van Nuys   West LA  West Valley  Wilshire
77th Street -0.053149 -0.055667    -0.055145 -0.057378
Central     -0.058894 -0.061685    -0.061107 -0.063580
Devonshire  -0.042487 -0.044500    -0.044083 -0.045868
Foothill    -0.038400 -0.040220    -0.039843 -0.041456
Harbor      -0.041542 -0.043510    -0.043103 -0.044847
Hollenbeck  -0.040016 -0.041912    -0.041519 -0.043200
Hollywood   -0.049038 -0.051362    -0.050881 -0.052940
Mission     -0.041756 -0.043734    -0.043325 -0.045079
N Hollywood -0.046047 -0.048228    -0.047777 -0.049711
Newton      -0.047780 -0.050043    -0.049575 -0.051581
Northeast   -0.043940 -0.046022    -0.045591 -0.047437
Olympic     -0.048145 -0.050426    -0.049954 -0.051976
Pacific     -0.050118 -0.052493    -0.052001 -0.054106
Rampart     -0.046231 -0.048421    -0.047968 -0.049909
Southeast   -0.047317 -0.049558    -0.049094 -0.051082
Southwest   -0.050730 -0.053133    -0.052636 -0.054766
Topanga     -0.042292 -0.044296    -0.043881 -0.045657
Van Nuys     1.000000 -0.044621    -0.044203 -0.045993
West LA     -0.044621  1.000000    -0.046298 -0.048172
West Valley -0.044203 -0.046298     1.000000 -0.047721
Wilshire    -0.045993 -0.048172    -0.047721  1.000000

[21 rows x 21 columns]

In [ ]:
df.columns

Index(['area', 'victim_age', 'THEFT OF IDENTITY', '77th Street', 'Central',
       'Devonshire', 'Foothill', 'Harbor', 'Hollenbeck', 'Hollywood',
       'Mission', 'N Hollywood', 'Newton', 'Northeast', 'Olympic', 'Pacific',
       'Rampart', 'Southeast', 'Southwest', 'Topanga', 'Van Nuys', 'West LA',
       'West Valley', 'Wilshire'],
      dtype='object')

In [ ]:
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
X = df.drop(['THEFT OF IDENTITY','area','victim_age'], axis=1)

# y contains the dependent variable 'THEFT OF IDENTITY'
y = df['THEFT OF IDENTITY']

# Compute VIF for each variable
vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print("\nVIF:")
print(vif_data)

# Remove variables with high VIF
# You may need to adjust the threshold based on your specific requirements
high_vif_variables = vif_data[vif_data['VIF'] > 10]['Variable']
X = X.drop(columns=high_vif_variables)

# Add a constant term for the intercept in the model
X = sm.add_constant(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an OLS regression model
model = sm.OLS(y_train, X_train)

# Fit the model to the training data
results = model.fit()

# Print the regression summary
print("\nRegression Summary:")
print(results.summary())

# Make predictions on the testing data
X_test = sm.add_constant(X_test)  # Add constant for testing data
y_pred = results.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print('\nMean Squared Error:', mse)

VIF:
       Variable  VIF
0   77th Street  1.0
1       Central  1.0
2    Devonshire  1.0
3      Foothill  1.0
4        Harbor  1.0
5    Hollenbeck  1.0
6     Hollywood  1.0
7       Mission  1.0
8   N Hollywood  1.0
9        Newton  1.0
10    Northeast  1.0
11      Olympic  1.0
12      Pacific  1.0
13      Rampart  1.0
14    Southeast  1.0
15    Southwest  1.0
16      Topanga  1.0
17     Van Nuys  1.0
18      West LA  1.0
19  West Valley  1.0
20     Wilshire  1.0

Regression Summary:
                            OLS Regression Results
==============================================================================
Dep. Variable:      THEFT OF IDENTITY   R-squared:                       0.011
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     101.3
Date:                Tue, 30 Jan 2024   Prob (F-statistic):               0.00
Time:                        10:13:03   Log-Likelihood:                -35150.
No. Observations:              188028   AIC:                         7.034e+04
Df Residuals:                  188007   BIC:                         7.055e+04
Df Model:                          20
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           0.0921      0.001    140.886      0.000       0.091       0.093
77th Street     0.0504      0.003     19.009      0.000       0.045       0.056
Central        -0.0484      0.002    -19.970      0.000      -0.053      -0.044
Devonshire      0.0047      0.003      1.446      0.148      -0.002       0.011
Foothill        0.0407      0.004     11.399      0.000       0.034       0.048
Harbor         -0.0193      0.003     -5.833      0.000      -0.026      -0.013
Hollenbeck      0.0141      0.003      4.116      0.000       0.007       0.021
Hollywood      -0.0310      0.003    -10.859      0.000      -0.037      -0.025
Mission         0.0218      0.003      6.584      0.000       0.015       0.028
N Hollywood     0.0025      0.003      0.834      0.404      -0.003       0.008
Newton          0.0213      0.003      7.302      0.000       0.016       0.027
Northeast      -0.0230      0.003     -7.289      0.000      -0.029      -0.017
Olympic        -0.0241      0.003     -8.293      0.000      -0.030      -0.018
Pacific        -0.0294      0.003    -10.486      0.000      -0.035      -0.024
Rampart         0.0143      0.003      4.740      0.000       0.008       0.020
Southeast       0.0626      0.003     21.366      0.000       0.057       0.068
Southwest       0.0343      0.003     12.379      0.000       0.029       0.040
Topanga         0.0183      0.003      5.605      0.000       0.012       0.025
Van Nuys        0.0072      0.003      2.218      0.027       0.001       0.014
West LA        -0.0060      0.003     -1.936      0.053      -0.012    7.35e-05
West Valley     0.0048      0.003      1.527      0.127      -0.001       0.011
Wilshire       -0.0236      0.003     -7.824      0.000      -0.030      -0.018
==============================================================================
Omnibus:                    98940.786   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           468762.969
Skew:                           2.717   Prob(JB):                         0.00
Kurtosis:                       8.505   Cond. No.                     5.47e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.6e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

Mean Squared Error: 0.08420165171480368